import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Download, Images, LockKeyhole, Sparkles, Trash2 } from 'lucide-react';
import { BlobWriter, Uint8ArrayReader, ZipWriter } from '@zip.js/zip.js';
import { UploadZone } from './components/UploadZone'; import { CompressionControls } from './components/CompressionControls'; import { AdvancedSettings } from './components/AdvancedSettings'; import { EngineBadge } from './components/EngineBadge'; import { BatchStats } from './components/BatchStats'; import { ImageCard } from './components/ImageCard';
import { ACCEPTED_TYPES, readBrowserMetadata, uniqueWebpNames } from './lib/files'; import { CompressionManager } from './lib/compression-manager'; import type { CompressionMode, CompressionSettings, ImageItem, ResizeOptions } from './types'; import { useWebGPU } from './hooks/useWebGPU';

const defaultResize: ResizeOptions = { kind:'original', maintainAspectRatio:true, preventEnlargement:true };
function ownedBuffer(bytes: Uint8Array): ArrayBuffer { const copy = new Uint8Array(bytes.byteLength); copy.set(bytes); return copy.buffer; }

export default function App() {
  const { available: gpu, checking } = useWebGPU(); const manager = useRef<CompressionManager | null>(null); const itemsRef = useRef<ImageItem[]>([]);
  const [items,setItems]=useState<ImageItem[]>([]); const [mode,setMode]=useState<CompressionMode>('custom'); const [quality,setQuality]=useState(85); const [auto,setAuto]=useState(false); const [resize,setResize]=useState<ResizeOptions>({...defaultResize});
  useEffect(()=>{itemsRef.current=items;},[items]);
  useEffect(()=>{ manager.current?.destroy(); manager.current=new CompressionManager(gpu); return()=>{ manager.current?.destroy(); manager.current=null; }; },[gpu]);
  useEffect(()=>()=>itemsRef.current.forEach(i=>URL.revokeObjectURL(i.previewUrl)),[]);
  const settings:CompressionSettings=useMemo(()=>({mode,quality,smartThreshold:.98,resize}),[mode,quality,resize]);

  const compressOne=useCallback(async(id:string, customSettings=settings)=>{ const item=itemsRef.current.find(i=>i.id===id); if(!item||!manager.current||item.status==='compressing')return; setItems(xs=>xs.map(x=>x.id===id?{...x,status:'compressing',progress:5,error:undefined}:x)); try{const result=await manager.current.compress(item.file,customSettings,p=>setItems(xs=>xs.map(x=>x.id===id?{...x,progress:p}:x)));setItems(xs=>xs.map(x=>x.id===id?{...x,status:'done',progress:100,result}:x));}catch(e){setItems(xs=>xs.map(x=>x.id===id?{...x,status:'error',progress:0,error:e instanceof Error?e.message:String(e)}:x));}},[settings]);
  const addFiles=useCallback(async(files:File[])=>{ const valid=files.filter(f=>ACCEPTED_TYPES.has(f.type)); const added:ImageItem[]=valid.map(file=>({id:crypto.randomUUID(),file,previewUrl:URL.createObjectURL(file),meta:null,status:'queued',progress:0})); if(!added.length)return; setItems(xs=>[...xs,...added]); for(const it of added){try{const meta=await readBrowserMetadata(it.file);setItems(xs=>xs.map(x=>x.id===it.id?{...x,meta}:x));}catch{setItems(xs=>xs.map(x=>x.id===it.id?{...x,status:'error',error:'Could not decode image metadata'}:x));}} if(auto) requestAnimationFrame(()=>added.forEach(it=>compressOne(it.id,settings))); },[auto,compressOne,settings]);
  const clear=()=>{items.forEach(i=>URL.revokeObjectURL(i.previewUrl));setItems([]);};
  const remove=(id:string)=>setItems(xs=>{const hit=xs.find(x=>x.id===id);if(hit)URL.revokeObjectURL(hit.previewUrl);return xs.filter(x=>x.id!==id);});
  const download=(item:ImageItem)=>{if(!item.result)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ownedBuffer(item.result.bytes)],{type:'image/webp'}));a.download=item.file.name.replace(/\.[^.]+$/,'')+'.webp';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
  const downloadAll=async()=>{const done=items.filter(i=>i.result);if(!done.length)return;if(done.length===1){download(done[0]);return;}const names=uniqueWebpNames(done.map(i=>i.file));const zip=new ZipWriter(new BlobWriter('application/zip'));for(let i=0;i<done.length;i++)await zip.add(names[i],new Uint8ArrayReader(done[i].result!.bytes));const blob=await zip.close();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='compressed-images.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
  const busy=items.some(i=>i.status==='compressing'); const done=items.filter(i=>i.result).length;

  return <div className="min-h-screen pb-28"><header className="border-b bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-4"><div className="flex items-center gap-2 font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-950 text-white"><Images size={18}/></span>Compress Image</div><div className="flex items-center gap-2"><span className="hidden items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-700 sm:inline-flex"><LockKeyhole size={13}/>Local only</span><EngineBadge gpu={gpu} checking={checking}/></div></div></header>
  <main className="mx-auto max-w-6xl space-y-6 px-4 py-10"><section className="max-w-3xl"><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-sky-50 px-3 py-1 text-xs font-medium text-sky-700"><Sparkles size={13}/>Private by design</div><h1 className="text-4xl font-bold tracking-tight sm:text-5xl">Compress images without uploading them</h1><p className="mt-4 max-w-2xl text-lg text-slate-600">Create smaller WebP images directly in your browser. Your images never leave your device.</p></section>
  <UploadZone onFiles={addFiles}/><div className="grid gap-4 lg:grid-cols-[1.4fr_1fr]"><CompressionControls mode={mode} quality={quality} auto={auto} onMode={setMode} onQuality={setQuality} onAuto={setAuto}/><AdvancedSettings value={resize} onChange={setResize}/></div>{items.length>0&&<><BatchStats items={items}/><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Batch <span className="text-slate-400">{items.length}</span></h2><button onClick={clear} className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-slate-950"><Trash2 size={16}/>Clear all</button></div><div className="grid gap-4 lg:grid-cols-2">{items.map(item=><ImageCard key={item.id} item={item} onRemove={()=>remove(item.id)} onDownload={()=>download(item)}/>)}</div></>}</main>
  {items.length>0&&<div className="fixed inset-x-0 bottom-0 border-t bg-white/95 p-3 shadow-[0_-8px_30px_rgba(15,23,42,.08)] backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3"><div className="text-sm text-slate-500">{done}/{items.length} compressed</div><div className="flex gap-2"><button disabled={busy} onClick={()=>items.filter(i=>i.status!=='compressing').forEach(i=>compressOne(i.id))} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">Compress All</button><button disabled={!done} onClick={downloadAll} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-medium disabled:opacity-50"><Download size={16}/>Download All</button></div></div></div>}</div>;
}
